# Generated by Django 2.2.6 on 2019-11-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destName', models.CharField(default='', max_length=100)),
                ('destPrice', models.IntegerField()),
                ('destDesc', models.TextField(default='')),
                ('destImage', models.ImageField(upload_to='images')),
                ('destOffer', models.BooleanField(default=False)),
            ],
        ),
    ]
